import { StyleSheet } from 'react-native';

export const returnDisputeStyles = StyleSheet.create({
modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    keyboardView: {
        alignSelf: 'stretch',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        backgroundColor: '#fff',
        borderRadius: 20,
        width: '92%',
        maxHeight: '85%',
        maxWidth: 500,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 10,
    },
    scrollContent: {
        paddingBottom: 20,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 16,
        paddingHorizontal: 20,
        backgroundColor: '#FEF2F2',
        borderBottomWidth: 2,
        borderBottomColor: '#FECACA',
    },
    headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    headerIcon: {
        fontSize: 24,
        marginRight: 10,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#DC2626',
        flex: 1,
    },
    closeButton: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#FEE2E2',
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 10,
    },
    closeButtonText: {
        fontSize: 20,
        color: '#DC2626',
        fontWeight: 'bold',
    },
    itemInfo: {
        padding: 16,
        backgroundColor: '#F9FAFB',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    itemTitle: {
        fontSize: 17,
        fontWeight: 'bold',
        color: '#1F2937',
        marginBottom: 4,
    },
    itemSubtitle: {
        fontSize: 14,
        color: '#6B7280',
    },
    section: {
        padding: 16,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#1F2937',
        marginBottom: 4,
    },
    sectionSubtitle: {
        fontSize: 13,
        color: '#6B7280',
        marginBottom: 15,
    },
    issueTypesContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    issueTypeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#E5E7EB',
        backgroundColor: '#fff',
        gap: 8,
    },
    issueTypeButtonActive: {
        borderColor: '#DC2626',
        backgroundColor: '#FEE2E2',
    },
    issueTypeEmoji: {
        fontSize: 20,
    },
    issueTypeText: {
        fontSize: 14,
        color: '#6B7280',
        fontWeight: '600',
    },
    issueTypeTextActive: {
        color: '#DC2626',
    },
    photosContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    photoWrapper: {
        position: 'relative',
        width: 100,
        height: 100,
    },
    photo: {
        width: 100,
        height: 100,
        borderRadius: 10,
    },
    removePhotoButton: {
        position: 'absolute',
        top: -5,
        right: -5,
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#DC2626',
        justifyContent: 'center',
        alignItems: 'center',
    },
    removePhotoText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    addPhotoButton: {
        width: 100,
        height: 100,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#E5E7EB',
        borderStyle: 'dashed',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F9FAFB',
    },
    addPhotoIcon: {
        fontSize: 30,
        marginBottom: 5,
    },
    addPhotoText: {
        fontSize: 12,
        color: '#6B7280',
        fontWeight: '600',
    },
    observationInput: {
        borderWidth: 1,
        borderColor: '#E5E7EB',
        borderRadius: 10,
        padding: 15,
        fontSize: 14,
        color: '#1F2937',
        minHeight: 120,
        backgroundColor: '#F9FAFB',
    },
    warningBox: {
        flexDirection: 'row',
        backgroundColor: '#FEF3C7',
        padding: 15,
        marginHorizontal: 20,
        marginBottom: 20,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#F59E0B',
    },
    warningIcon: {
        fontSize: 24,
        marginRight: 10,
    },
    warningContent: {
        flex: 1,
    },
    warningTitle: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#92400E',
        marginBottom: 5,
    },
    warningText: {
        fontSize: 13,
        color: '#92400E',
    },
    buttonsContainer: {
        flexDirection: 'row',
        padding: 20,
        gap: 10,
    },
    cancelButton: {
        flex: 1,
        paddingVertical: 15,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#E5E7EB',
        backgroundColor: '#fff',
        alignItems: 'center',
    },
    cancelButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#6B7280',
    },
    submitButton: {
        flex: 1,
        paddingVertical: 15,
        borderRadius: 10,
        backgroundColor: '#DC2626',
        alignItems: 'center',
    },
    submitButtonDisabled: {
        backgroundColor: '#FCA5A5',
    },
    submitButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#fff',
    },
});
