import { StyleSheet } from 'react-native';

export const reviewStyles = StyleSheet.create({
modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
    },
    scrollContainer: {
        flexGrow: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContent: {
        backgroundColor: '#fff',
        borderRadius: 24,
        width: '100%',
        maxWidth: 500,
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 8},
        shadowOpacity: 0.4,
        shadowRadius: 16,
        elevation: 12,
    },
    header: {
        backgroundColor: '#10B981',
        paddingVertical: 20,
        paddingHorizontal: 20,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#fff',
        textAlign: 'center',
    },
    userInfoContainer: {
        alignItems: 'center',
        paddingVertical: 30,
        paddingHorizontal: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    userAvatar: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: '#10B981',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
    },
    userAvatarText: {
        fontSize: 36,
        fontWeight: 'bold',
        color: '#fff',
    },
    userName: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#1F2937',
        marginBottom: 8,
    },
    currentRatingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginBottom: 12,
    },
    currentRatingText: {
        fontSize: 16,
    },
    currentRatingValue: {
        fontSize: 16,
        fontWeight: '600',
        color: '#666',
    },
    itemTitle: {
        fontSize: 16,
        color: '#666',
        fontStyle: 'italic',
    },
    starsContainer: {
        padding: 30,
        alignItems: 'center',
        backgroundColor: '#F9FAFB',
    },
    starsLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 20,
    },
    starsRow: {
        flexDirection: 'row',
        gap: 12,
        marginBottom: 16,
    },
    star: {
        fontSize: 48,
    },
    ratingText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#10B981',
        marginTop: 8,
    },
    reasonContainer: {
        padding: 20,
        backgroundColor: '#FEF3C7',
        borderTopWidth: 3,
        borderTopColor: '#F59E0B',
    },
    reasonLabel: {
        fontSize: 15,
        fontWeight: '600',
        color: '#92400E',
        marginBottom: 12,
    },
    reasonInput: {
        backgroundColor: '#fff',
        padding: 15,
        borderRadius: 12,
        fontSize: 15,
        color: '#1F2937',
        minHeight: 80,
        textAlignVertical: 'top',
        borderWidth: 2,
        borderColor: '#F59E0B',
    },
    inputRequired: {
        borderColor: '#F59E0B',
    },
    commentContainer: {
        padding: 20,
    },
    commentLabel: {
        fontSize: 15,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 12,
    },
    commentInput: {
        backgroundColor: '#F9FAFB',
        padding: 15,
        borderRadius: 12,
        fontSize: 15,
        color: '#1F2937',
        minHeight: 100,
        textAlignVertical: 'top',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    charCount: {
        fontSize: 12,
        color: '#9CA3AF',
        textAlign: 'right',
        marginTop: 6,
    },
    buttonsContainer: {
        padding: 20,
        gap: 12,
    },
    submitButton: {
        backgroundColor: '#10B981',
        paddingVertical: 18,
        borderRadius: 16,
        alignItems: 'center',
        shadowColor: '#10B981',
        shadowOffset: {width: 0, height: 4},
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    submitButtonDisabled: {
        backgroundColor: '#9CA3AF',
        opacity: 0.6,
    },
    submitButtonText: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
    },
    selectStarsHint: {
        backgroundColor: '#F3F4F6',
        paddingVertical: 18,
        borderRadius: 16,
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#E5E7EB',
        borderStyle: 'dashed',
    },
    selectStarsText: {
        fontSize: 16,
        color: '#6B7280',
        fontWeight: '600',
    },
    skipButton: {
        backgroundColor: '#fff',
        paddingVertical: 16,
        borderRadius: 16,
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#E5E7EB',
    },
    skipButtonText: {
        fontSize: 16,
        fontWeight: '600',
        color: '#6B7280',
    },
    infoText: {
        fontSize: 13,
        color: '#6B7280',
        textAlign: 'center',
        lineHeight: 20,
        paddingHorizontal: 20,
        paddingBottom: 20,
        fontStyle: 'italic',
    },
});
