// Mapeamento de ícones e cores por categoria
export const categoryConfig = {
    // 1. Electrónicos, Fotografía y Audio
    'Electrónicos': { icon: '📱', color: '#FF6B6B', gradient: ['#FF6B6B', '#EE5A6F'] },
    'Cámaras y Lentes': { icon: '📷', color: '#FF6B6B', gradient: ['#FF6B6B', '#EE5A6F'] },
    'Video y Streaming': { icon: '🎥', color: '#FF6B6B', gradient: ['#FF6B6B', '#EE5A6F'] },
    'Audio y Música': { icon: '🎵', color: '#FF6B6B', gradient: ['#FF6B6B', '#EE5A6F'] },
    'Computación': { icon: '💻', color: '#FF6B6B', gradient: ['#FF6B6B', '#EE5A6F'] },
    'Realidad Virtual/Gaming': { icon: '🎮', color: '#FF6B6B', gradient: ['#FF6B6B', '#EE5A6F'] },
    // 2. Herramientas y Equipos para Casa
    'Herramientas': { icon: '🔨', color: '#A29BFE', gradient: ['#A29BFE', '#8B7FEE'] },
    'Reforma y Construcción': { icon: '🔨', color: '#A29BFE', gradient: ['#A29BFE', '#8B7FEE'] },
    'Jardinería': { icon: '🌱', color: '#26DE81', gradient: ['#26DE81', '#20BF6B'] },
    'Limpieza y Mantenimiento': { icon: '🧹', color: '#48DBFB', gradient: ['#48DBFB', '#0FB9E0'] },
    'Medición y Prueba': { icon: '📐', color: '#A29BFE', gradient: ['#A29BFE', '#8B7FEE'] },
    'Seguridad y Protección': { icon: '🦺', color: '#FFA500', gradient: ['#FFA500', '#FF8C00'] },
    // 3. Deportes y Ocio
    'Deportes': { icon: '⚽', color: '#FF9F43', gradient: ['#FF9F43', '#FF8C00'] },
    'Equipos Acuáticos': { icon: '🏄', color: '#48DBFB', gradient: ['#48DBFB', '#0FB9E0'] },
    'Deportes de Aventura': { icon: '🏔️', color: '#26DE81', gradient: ['#26DE81', '#20BF6B'] },
    'Deportes Colectivos': { icon: '🏀', color: '#FF9F43', gradient: ['#FF9F43', '#FF8C00'] },
    'Fitness y Gimnasio': { icon: '💪', color: '#E056FD', gradient: ['#E056FD', '#C739E5'] },
    'Deportes de Invierno': { icon: '⛷️', color: '#48DBFB', gradient: ['#48DBFB', '#0FB9E0'] },
    // 4. Moda y Accesorios
    'Ropa': { icon: '👕', color: '#E056FD', gradient: ['#E056FD', '#C739E5'] },
    'Vestuario de Fiesta': { icon: '👗', color: '#E056FD', gradient: ['#E056FD', '#C739E5'] },
    'Accesorios de Lujo': { icon: '👜', color: '#FFD700', gradient: ['#FFD700', '#FFC700'] },
    'Moda Deportiva/Funcional': { icon: '👟', color: '#FF9F43', gradient: ['#FF9F43', '#FF8C00'] },
    'Bodas y Eventos': { icon: '💍', color: '#FFB6C1', gradient: ['#FFB6C1', '#FF69B4'] },
    // 5. Artículos para Bebés y Niños
    'Bebés y Niños': { icon: '👶', color: '#FFC312', gradient: ['#FFC312', '#EEA500'] },
    'Viaje y Transporte': { icon: '🚼', color: '#FFC312', gradient: ['#FFC312', '#EEA500'] },
    'Ocio Infantil': { icon: '🧸', color: '#FF6B6B', gradient: ['#FF6B6B', '#EE5A6F'] },
    'Equipos de Apoyo': { icon: '🍼', color: '#48DBFB', gradient: ['#48DBFB', '#0FB9E0'] },
    // 6. Eventos y Fiestas
    'Fiestas': { icon: '🎉', color: '#FF6348', gradient: ['#FF6348', '#E84118'] },
    'Mobiliario y Decoración': { icon: '🪑', color: '#FFC312', gradient: ['#FFC312', '#EEA500'] },
    'Utensilios de cocina': { icon: '👩‍🍳', color: '#26DE81', gradient: ['#26DE81', '#20BF6B'] },
    'Servicios de Bar/Cocina': { icon: '🍹', color: '#26DE81', gradient: ['#26DE81', '#20BF6B'] },
    'Juegos y Entretenimiento': { icon: '🎯', color: '#FF9F43', gradient: ['#FF9F43', '#FF8C00'] },
    'Estructura para Eventos': { icon: '⛺', color: '#A29BFE', gradient: ['#A29BFE', '#8B7FEE'] },
    // 7. Transporte y Vehículos
    'Accesorios de Vehículos': { icon: '🚗', color: '#48DBFB', gradient: ['#48DBFB', '#0FB9E0'] },
    'Movilidad Personal': { icon: '🚲', color: '#26DE81', gradient: ['#26DE81', '#20BF6B'] },
    'Viaje en Coche': { icon: '🧳', color: '#FF9F43', gradient: ['#FF9F43', '#FF8C00'] },
    'Mantenimiento Vehicular': { icon: '🔧', color: '#A29BFE', gradient: ['#A29BFE', '#8B7FEE'] },
    // 8. Hobbies y Educación
    'Hobbies y Educación': { icon: '📚', color: '#FFC312', gradient: ['#FFC312', '#EEA500'] },
    'Artes y Artesanía': { icon: '🎨', color: '#E056FD', gradient: ['#E056FD', '#C739E5'] },
    'Instrumentos Musicales': { icon: '🎸', color: '#FF6B6B', gradient: ['#FF6B6B', '#EE5A6F'] },
    'Libros y Cursos': { icon: '📖', color: '#48DBFB', gradient: ['#48DBFB', '#0FB9E0'] },
    // Genéricos
    'Muebles': { icon: '🛋️', color: '#FFC312', gradient: ['#FFC312', '#EEA500'] },
    'Jardín': { icon: '🌱', color: '#26DE81', gradient: ['#26DE81', '#20BF6B'] },
    'Otros': { icon: '📦', color: '#95A5A6', gradient: ['#95A5A6', '#7F8C8D'] },
    // English translations
    'Electronics': { icon: '📱', color: '#FF6B6B', gradient: ['#FF6B6B', '#EE5A6F'] },
    'Cameras and Lenses': { icon: '📷', color: '#FF6B6B', gradient: ['#FF6B6B', '#EE5A6F'] },
    'Video and Streaming': { icon: '🎥', color: '#FF6B6B', gradient: ['#FF6B6B', '#EE5A6F'] },
    'Audio and Music': { icon: '🎵', color: '#FF6B6B', gradient: ['#FF6B6B', '#EE5A6F'] },
    'Computing': { icon: '💻', color: '#FF6B6B', gradient: ['#FF6B6B', '#EE5A6F'] },
    'Virtual Reality/Gaming': { icon: '🎮', color: '#FF6B6B', gradient: ['#FF6B6B', '#EE5A6F'] },
    'Tools': { icon: '🔨', color: '#A29BFE', gradient: ['#A29BFE', '#8B7FEE'] },
    'Reform and Construction': { icon: '🔨', color: '#A29BFE', gradient: ['#A29BFE', '#8B7FEE'] },
    'Gardening': { icon: '🌱', color: '#26DE81', gradient: ['#26DE81', '#20BF6B'] },
    'Cleaning and Maintenance': { icon: '🧹', color: '#48DBFB', gradient: ['#48DBFB', '#0FB9E0'] },
    'Measurement and Testing': { icon: '📐', color: '#A29BFE', gradient: ['#A29BFE', '#8B7FEE'] },
    'Safety and Protection': { icon: '🦺', color: '#FFA500', gradient: ['#FFA500', '#FF8C00'] },
    'Sports': { icon: '⚽', color: '#FF9F43', gradient: ['#FF9F43', '#FF8C00'] },
    'Water Equipment': { icon: '🏄', color: '#48DBFB', gradient: ['#48DBFB', '#0FB9E0'] },
    'Adventure Sports': { icon: '🏔️', color: '#26DE81', gradient: ['#26DE81', '#20BF6B'] },
    'Team Sports': { icon: '🏀', color: '#FF9F43', gradient: ['#FF9F43', '#FF8C00'] },
    'Fitness and Gym': { icon: '💪', color: '#E056FD', gradient: ['#E056FD', '#C739E5'] },
    'Winter Sports': { icon: '⛷️', color: '#48DBFB', gradient: ['#48DBFB', '#0FB9E0'] },
    'Clothing': { icon: '👕', color: '#E056FD', gradient: ['#E056FD', '#C739E5'] },
    'Party Wear': { icon: '👗', color: '#E056FD', gradient: ['#E056FD', '#C739E5'] },
    'Luxury Accessories': { icon: '👜', color: '#FFD700', gradient: ['#FFD700', '#FFC700'] },
    'Sports/Functional Fashion': { icon: '👟', color: '#FF9F43', gradient: ['#FF9F43', '#FF8C00'] },
    'Weddings and Events': { icon: '💍', color: '#FFB6C1', gradient: ['#FFB6C1', '#FF69B4'] },
    'Babies and Children': { icon: '👶', color: '#FFC312', gradient: ['#FFC312', '#EEA500'] },
    'Travel and Transport': { icon: '🚼', color: '#FFC312', gradient: ['#FFC312', '#EEA500'] },
    'Children Leisure': { icon: '🧸', color: '#FF6B6B', gradient: ['#FF6B6B', '#EE5A6F'] },
    'Support Equipment': { icon: '🍼', color: '#48DBFB', gradient: ['#48DBFB', '#0FB9E0'] },
    'Parties': { icon: '🎉', color: '#FF6348', gradient: ['#FF6348', '#E84118'] },
    'Furniture and Decoration': { icon: '🪑', color: '#FFC312', gradient: ['#FFC312', '#EEA500'] },
    'Kitchen utensils': { icon: '👩‍🍳', color: '#26DE81', gradient: ['#26DE81', '#20BF6B'] },
    'Bar/Kitchen Services': { icon: '🍹', color: '#26DE81', gradient: ['#26DE81', '#20BF6B'] },
    'Games and Entertainment': { icon: '🎯', color: '#FF9F43', gradient: ['#FF9F43', '#FF8C00'] },
    'Event Structure': { icon: '⛺', color: '#A29BFE', gradient: ['#A29BFE', '#8B7FEE'] },
    'Vehicle Accessories': { icon: '🚗', color: '#48DBFB', gradient: ['#48DBFB', '#0FB9E0'] },
    'Personal Mobility': { icon: '🚲', color: '#26DE81', gradient: ['#26DE81', '#20BF6B'] },
    'Car Travel': { icon: '🧳', color: '#FF9F43', gradient: ['#FF9F43', '#FF8C00'] },
    'Vehicle Maintenance': { icon: '🔧', color: '#A29BFE', gradient: ['#A29BFE', '#8B7FEE'] },
    'Hobbies and Education': { icon: '📚', color: '#FFC312', gradient: ['#FFC312', '#EEA500'] },
    'Arts and Crafts': { icon: '🎨', color: '#E056FD', gradient: ['#E056FD', '#C739E5'] },
    'Musical Instruments': { icon: '🎸', color: '#FF6B6B', gradient: ['#FF6B6B', '#EE5A6F'] },
    'Books and Courses': { icon: '📖', color: '#48DBFB', gradient: ['#48DBFB', '#0FB9E0'] },
    'Furniture': { icon: '🛋️', color: '#FFC312', gradient: ['#FFC312', '#EEA500'] },
    'Garden': { icon: '🌱', color: '#26DE81', gradient: ['#26DE81', '#20BF6B'] },
    'Others': { icon: '📦', color: '#95A5A6', gradient: ['#95A5A6', '#7F8C8D'] },
};
// Categorias principais para seleção
export const categories = [
    'Todos',
    // 1. Electrónicos
    'Electrónicos',
    'Cámaras y Lentes',
    'Video y Streaming',
    'Audio y Música',
    'Computación',
    'Realidad Virtual/Gaming',
    // 2. Herramientas
    'Herramientas',
    'Reforma y Construcción',
    'Jardinería',
    'Limpieza y Mantenimiento',
    'Medición y Prueba',
    'Seguridad y Protección',
    // 3. Deportes
    'Deportes',
    'Equipos Acuáticos',
    'Deportes de Aventura',
    'Deportes Colectivos',
    'Fitness y Gimnasio',
    'Deportes de Invierno',
    // 4. Moda
    'Ropa',
    'Vestuario de Fiesta',
    'Accesorios de Lujo',
    'Moda Deportiva/Funcional',
    'Bodas y Eventos',
    // 5. Bebés y Niños
    'Bebés y Niños',
    'Viaje y Transporte',
    'Ocio Infantil',
    'Equipos de Apoyo',
    // 6. Eventos
    'Fiestas',
    'Mobiliario y Decoración',
    'Utensilios de cocina',
    'Servicios de Bar/Cocina',
    'Juegos y Entretenimiento',
    'Estructura para Eventos',
    // 7. Vehículos
    'Accesorios de Vehículos',
    'Movilidad Personal',
    'Viaje en Coche',
    'Mantenimiento Vehicular',
    // 8. Hobbies
    'Hobbies y Educación',
    'Artes y Artesanía',
    'Instrumentos Musicales',
    'Libros y Cursos',
    // Genéricos
    'Muebles',
    'Jardín',
    'Otros'
];
// Subcategorias (em espanhol)
export const subcategories = {
    'Electrónicos': [
        'Cámaras DSLR/Mirrorless',
        'Lentes (zoom, prime)',
        'Cámaras de Acción (GoPro)',
        'Drones',
        'Cámaras Instantáneas',
        'Portátiles',
        'Tablets',
        'Monitores',
        'Proyectores',
        'Consolas de Juegos',
        'Auriculares VR',
    ],
    'Cámaras y Lentes': [
        'Cámaras DSLR',
        'Cámaras Mirrorless',
        'Lentes Zoom',
        'Lentes Prime',
        'Cámaras de Acción',
        'Drones',
        'Cámaras Instantáneas',
    ],
    'Video y Streaming': [
        'Cámaras de Video Profesionales',
        'Estabilizadores (Gimbals)',
        'Trípodes',
        'Luces de Anillo',
        'Softboxes',
        'Micrófonos',
    ],
    'Audio y Música': [
        'Auriculares de Alta Fidelidad',
        'Altavoces Portátiles',
        'Mesas de Mezclas',
        'Micrófonos para Podcast',
    ],
    'Herramientas': [
        'Taladros',
        'Atornilladores',
        'Sierras',
        'Lijadoras',
        'Compresores de Aire',
        'Hidrolimpiadoras',
    ],
    'Reforma y Construcción': [
        'Taladros',
        'Atornilladores',
        'Sierras de Calar',
        'Sierras Circulares',
        'Lijadoras',
        'Compresores de Aire',
    ],
    'Jardinería': [
        'Cortacéspedes',
        'Recortadores de Setos',
        'Sopladores de Hojas',
        'Herramientas Manuales',
    ],
    'Limpieza y Mantenimiento': [
        'Hidrolimpiadoras',
        'Extractoras de Alfombras',
        'Aspiradoras Industriales',
    ],
    'Deportes': [
        'Bicicletas',
        'Equipos de Camping',
        'Tablas de SUP',
        'Balones',
        'Pesas',
        'Cintas de Correr',
    ],
    'Equipos Acuáticos': [
        'Kayaks',
        'Tablas Stand-Up Paddle',
        'Snorkel y Máscaras',
        'Chalecos Salvavidas',
    ],
    'Deportes de Aventura': [
        'Tiendas de Campaña',
        'Sacos de Dormir',
        'Mochilas de Montaña',
        'Kit de Escalada',
    ],
    'Fitness y Gimnasio': [
        'Mancuernas',
        'Kettlebells',
        'Cintas de Correr',
        'Bicicletas Estáticas',
        'Esterillas de Yoga',
    ],
    'Ropa': [
        'Vestidos de Gala',
        'Esmóquines',
        'Disfraces',
        'Ropa de Época',
    ],
    'Vestuario de Fiesta': [
        'Vestidos de Gala',
        'Esmóquines',
        'Disfraces de Alta Calidad',
        'Ropa de Época',
    ],
    'Bodas y Eventos': [
        'Velos',
        'Coronas',
        'Accesorios de Novia',
        'Cajas de Transporte',
    ],
    'Bebés y Niños': [
        'Sillas de Coche',
        'Carritos de Bebé',
        'Cunas Portátiles',
        'Juguetes Educativos',
    ],
    'Ocio Infantil': [
        'Juguetes Educativos',
        'Piscinas Hinchables',
        'Castillos Inflables',
        'Disfraces de Personajes',
    ],
    'Fiestas': [
        'Mesas y Sillas',
        'Máquinas de Karaoke',
        'Tiradoras de Cerveza',
        'Carpas',
    ],
    'Mobiliario y Decoración': [
        'Mesas y Sillas',
        'Manteles',
        'Máquinas de Humo',
        'Luces LED Decorativas',
    ],
    'Utensilios de cocina': [
        'parrilla',
        'barbacoa portátil',
        'freidora de aire',
        'batidora de mano',
        'licuadora',
        'olla grande',
        'paellera',
        'máquina para hacer pasta',
        'sandwichera',
        'plancha eléctrica',
        'máquina de hacer waffles',
        'raclette',
        'fondue',
    ],
    'Servicios de Bar/Cocina': [
        'Máquinas de Café Espresso',
        'Tiradoras de Cerveza',
        'Utensilios de Buffet',
        'Sets de Fondue',
    ],
    'Accesorios de Vehículos': [
        'Portaequipajes de Techo',
        'Soportes para Bicicletas',
        'Cables de Batería',
    ],
    'Movilidad Personal': [
        'Bicicletas de Montaña',
        'Bicicletas Eléctricas',
        'Patinetes Eléctricos',
        'Hoverboards',
    ],
    'Hobbies y Educación': [
        'Máquinas de Coser',
        'Guitarras',
        'Teclados',
        'Libros Raros',
    ],
    'Artes y Artesanía': [
        'Máquinas de Coser',
        'Plotters de Corte',
        'Caballetes de Pintura',
        'Prensas Térmicas',
    ],
    'Instrumentos Musicales': [
        'Guitarras',
        'Teclados',
        'Baterías Electrónicas',
        'Amplificadores',
    ],
};
export const sortOptions = [
    { id: 'recent', label: 'Más Recientes', icon: '🕐' },
    { id: 'price_low', label: 'Menor Precio', icon: '💰' },
    { id: 'price_high', label: 'Mayor Precio', icon: '💎' },
    { id: 'title', label: 'A-Z', icon: '🔤' },
];
