import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    safeContainer: {
        flex: 1,
        backgroundColor: '#F8F9FA',
        paddingTop: Platform.OS === 'android' ? 25 : 0,
    },
    headerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#E8E8E8',
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F8F9FA',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E8E8E8',
    },
    backArrow: {
        fontSize: 22,
        color: '#333',
    },
    headerTitleContainer: {
        flex: 1,
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#2c4455',
    },
    headerSpacer: {
        width: 40,
    },
    container: {
        flex: 1,
        padding: 20,
        backgroundColor: '#F8F9FA',
    },
    label: {
        fontSize: 16,
        fontWeight: '600',
        marginTop: 15,
        marginBottom: 5,
    },
    sublabel: {
        fontSize: 13,
        color: '#666',
        marginBottom: 12,
        fontStyle: 'italic',
    },
    depositWarning: {
        fontSize: 12,
        color: '#FF9800',
        fontStyle: 'italic',
        marginBottom: 8,
        lineHeight: 18,
    },
    priceDepositRow: {
        flexDirection: 'row',
        gap: 15,
        marginBottom: 12,
    },
    priceDepositCol: {
        flex: 1,
    },
    photosSection: {
        marginTop: 20,
        marginBottom: 20,
    },
    actionButtonsContainer: {
        marginTop: 20,
        marginBottom: 10,
    },
    input: {
        borderWidth: 1,
        borderColor: '#ccc',
        padding: 10,
        borderRadius: 5,
        marginBottom: 10,
    },
    multilineInput: {
        height: 100,
        textAlignVertical: 'top',
    },
    pickerContainer: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 5,
        marginBottom: 10,
    },
    photosGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: 20,
        gap: 10,
    },
    photoContainer: {
        width: '31%',
        aspectRatio: 1,
    },
    photoPlaceholder: {
        alignSelf: 'stretch',
        height: '100%',
        borderWidth: 2,
        borderColor: '#ccc',
        borderStyle: 'dashed',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        overflow: 'hidden',
        position: 'relative',
    },
    photoPlaceholderPrimary: {
        borderColor: '#2c4455',
        borderWidth: 2,
        borderStyle: 'solid',
    },
    addPhotoContent: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    addPhotoIcon: {
        fontSize: 30,
        marginBottom: 5,
    },
    addPhotoText: {
        fontSize: 10,
        color: '#666',
        textAlign: 'center',
        fontWeight: '600',
    },
    previewImage: {
        alignSelf: 'stretch',
        height: '100%',
        borderRadius: 8,
        resizeMode: 'cover',
    },
    removePhotoButton: {
        position: 'absolute',
        top: 5,
        right: 5,
        backgroundColor: 'rgba(220, 53, 69, 0.9)',
        width: 24,
        height: 24,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
    },
    removePhotoText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    primaryBadge: {
        position: 'absolute',
        bottom: 5,
        left: 5,
        backgroundColor: 'rgba(44, 68, 85, 0.9)',
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 5,
    },
    primaryBadgeText: {
        color: '#fff',
        fontSize: 9,
        fontWeight: 'bold',
    },
    deliveryTypeContainer: {
        marginBottom: 20,
        gap: 12,
    },
    deliveryOption: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F5F5F5',
        padding: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#E0E0E0',
        position: 'relative',
    },
    deliveryOptionActive: {
        backgroundColor: '#E3F2FD',
        borderColor: '#2c4455',
    },
    deliveryOptionIcon: {
        fontSize: 24,
        marginRight: 12,
    },
    deliveryOptionText: {
        fontSize: 15,
        color: '#666',
        fontWeight: '500',
        flex: 1,
    },
    deliveryOptionTextActive: {
        color: '#2c4455',
        fontWeight: '700',
    },
    deliveryCheckmark: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#2c4455',
        justifyContent: 'center',
        alignItems: 'center',
    },
    deliveryCheckmarkText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    saveButton: {
        marginTop: 30,
        marginBottom: 15,
        borderRadius: 15,
        overflow: 'hidden',
        elevation: 8,
        shadowColor: '#10B981',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
    },
    saveButtonDisabled: {
        opacity: 0.7,
    },
    saveButtonGradient: {
        paddingVertical: 10,
        paddingHorizontal: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    deleteButton: {
        marginBottom: 10,
        borderRadius: 15,
        overflow: 'hidden',
        elevation: 8,
        shadowColor: '#dc3545',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
    },
    deleteButtonDisabled: {
        opacity: 0.7,
    },
    deleteButtonGradient: {
        paddingVertical: 10,
        paddingHorizontal: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
    },
    buttonIcon: {
        fontSize: 24,
    },
    buttonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },
    loadingAddressContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: '#F8F9FA',
        borderRadius: 8,
        marginBottom: 10,
        gap: 10,
    },
    loadingAddressText: {
        fontSize: 14,
        color: '#666',
        fontStyle: 'italic',
    },
    suggestionsContainer: {
        backgroundColor: '#fff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E8E8E8',
        marginBottom: 15,
        padding: 12,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    suggestionsTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#2c4455',
        marginBottom: 10,
    },
    suggestionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: '#F8F9FA',
        borderRadius: 8,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#E8E8E8',
    },
    suggestionIcon: {
        fontSize: 18,
        marginRight: 10,
    },
    suggestionText: {
        fontSize: 14,
        color: '#333',
        flex: 1,
    },
    selectedLocationContainer: {
        marginBottom: 15,
    },
    selectedLocationLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#2c4455',
        marginBottom: 8,
    },
    selectedLocationBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8F5E9',
        padding: 14,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#10B981',
    },
    selectedLocationIcon: {
        fontSize: 20,
        marginRight: 10,
    },
    selectedLocationText: {
        fontSize: 15,
        color: '#2c4455',
        fontWeight: '500',
        flex: 1,
    },
    clearLocationButton: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#dc3545',
        justifyContent: 'center',
        alignItems: 'center',
    },
    clearLocationText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    formGroup: {
        marginBottom: 25,
        paddingHorizontal: 0,
    },
});

