import { StyleSheet } from 'react-native';

export const itemCardStyles = StyleSheet.create({
    card: {
        backgroundColor: '#fff',
        borderRadius: 16,
        marginBottom: 20,
        overflow: 'hidden',
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 8,
    },
    categoryHeader: {
        backgroundColor: '#fff',
        paddingHorizontal: 0,
        paddingVertical: 8,
        paddingLeft: 14,
        paddingBottom: 6,
        marginBottom: 0,
        borderBottomColor: '#eee',
    },
    categoryLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: '#000',
        textTransform: 'capitalize',
    },
    cardImageContainer: {
        position: 'relative',
        width: '100%',
        height: 200,
        backgroundColor: '#f5f5f5',
        padding: 0,
        justifyContent: 'center',
        alignItems: 'center',
    },
    cardImage: {
        width: '100%',
        height: '100%',
        borderRadius: 0,
    },
    cardImagePlaceholder: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    placeholderIcon: {
        fontSize: 50,
        opacity: 0.6,
    },
    imageOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 60,
        backgroundColor: 'transparent',
    },
    pausedBadge: {
        position: 'absolute',
        top: 10,
        left: 10,
        backgroundColor: '#FF9800',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
    pausedBadgeText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
    },
    // Badge de Desconto
    discountBadge: {
        position: 'absolute',
        top: 10,
        right: 10,
        backgroundColor: '#FF6B00',
        paddingHorizontal: 8,
        paddingVertical: 5,
        borderRadius: 8,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.4,
        shadowRadius: 5,
        elevation: 6,
    },
    discountBadgeIcon: {
        fontSize: 11,
    },
    discountBadgeText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },
    cardContent: {
        padding: 14,
        paddingTop: 12,
        paddingBottom: 12,
    },
    cardTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#1a3a52',
        marginBottom: 6,
        lineHeight: 22,
    },
    cardDescription: {
        fontSize: 13,
        color: '#666',
        marginBottom: 10,
        lineHeight: 18,
    },
    distanceText: {
        fontSize: 12,
        color: '#10B981',
        fontWeight: '600',
        marginBottom: 8,
    },
    footerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    priceContainer: {
        flexDirection: 'row',
        alignItems: 'baseline',
    },
    priceSymbol: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#10B981',
        marginRight: 3,
    },
    cardPrice: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#10B981',
    },
    priceLabel: {
        fontSize: 12,
        color: '#10B981',
        marginLeft: 3,
        fontWeight: '500',
    },
    statusBadgeSmall: {
        backgroundColor: '#10B981',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 8,
        marginLeft: 8,
    },
    statusBadgeUnavailable: {
        backgroundColor: '#dc3545',
    },
    statusBadgeText: {
        color: '#fff',
        fontSize: 7,
        fontWeight: '600',
    },
    cardDivider: {
        height: 1,
        backgroundColor: '#E5E7EB',
        marginHorizontal: 0,
    },
    cardShine: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 2,
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
    },
    deliveryInfoText: {
        fontSize: 11,
        color: '#10B981',
        fontWeight: '600',
        marginTop: 4,
        marginBottom: 6,
    },
    deliveryBadge: {
        position: 'absolute',
        bottom: 12,
        left: 12,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        backgroundColor: '#3B82F6',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    deliveryBadgeText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
    },
});
