import { StyleSheet } from 'react-native';

export const itemCardStyles = StyleSheet.create({
    card: {
        width: '48%',
        backgroundColor: '#fff',
        borderRadius: 20,
        marginBottom: 15,
        overflow: 'hidden',
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.15,
        shadowRadius: 5,
    },
    cardImageContainer: {
        position: 'relative',
        width: '100%',
        height: 160,
        backgroundColor: '#f0f0f0',
    },
    cardImage: {
        width: '100%',
        height: '100%',
    },
    cardImagePlaceholder: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    placeholderIcon: {
        fontSize: 50,
        opacity: 0.6,
    },
    imageOverlay: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 60,
        backgroundColor: 'transparent',
    },
    availableBadge: {
        position: 'absolute',
        top: 10,
        right: 10,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(16, 185, 129, 0.95)',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 20,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
    },
    availableDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#fff',
        marginRight: 5,
    },
    availableBadgeText: {
        color: '#fff',
        fontSize: 9,
        fontWeight: 'bold',
    },
    unavailableBadge: {
        position: 'absolute',
        top: 10,
        right: 10,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(220, 53, 69, 0.95)',
        paddingHorizontal: 10,
        paddingVertical: 5,
        borderRadius: 20,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
    },
    unavailableDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: '#fff',
        marginRight: 5,
    },
    unavailableBadgeText: {
        color: '#fff',
        fontSize: 9,
        fontWeight: 'bold',
    },
    categoryIconBadge: {
        position: 'absolute',
        bottom: 10,
        left: 10,
        width: 36,
        height: 36,
        borderRadius: 18,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    categoryIconText: {
        fontSize: 20,
    },
    cardContent: {
        padding: 14,
    },
    cardTitle: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#1a3a52',
        marginBottom: 8,
        height: 40,
        lineHeight: 20,
    },
    locationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    locationIcon: {
        fontSize: 12,
        marginRight: 4,
    },
    cardLocation: {
        fontSize: 12,
        color: '#666',
        flex: 1,
        fontWeight: '500',
    },
    priceRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderTopWidth: 1,
        borderTopColor: '#F0F0F0',
        paddingTop: 10,
        marginTop: 5,
    },
    priceContainer: {
        flexDirection: 'row',
        alignItems: 'baseline',
        flex: 1,
    },
    priceSymbol: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#28a745',
        marginRight: 2,
    },
    cardPrice: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#28a745',
    },
    priceLabel: {
        fontSize: 12,
        color: '#666',
        marginLeft: 3,
        fontWeight: '500',
    },
    actionButton: {
        backgroundColor: '#2c4455',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 15,
        elevation: 2,
        shadowColor: '#2c4455',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
    },
    actionButtonText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
    },
    cardShine: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 2,
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
    },
});

