import { StyleSheet, Platform } from 'react-native';

export const mainMarketplaceStyles = StyleSheet.create({
    fullContainer: {
        flex: 1,
        backgroundColor: '#E8EAED',
        paddingTop: Platform.OS === 'android' ? 25 : 0,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#E8EAED',
    },
    loadingContent: {
        alignItems: 'center',
    },
    loadingText: {
        marginTop: 15,
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
    },
    loadingSubtext: {
        marginTop: 5,
        fontSize: 14,
        color: '#999',
    },
    headerContainer: {
        backgroundColor: '#10B981',
        paddingTop: 12,
        paddingBottom: 12,
        paddingHorizontal: 16,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
    },
    headerTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    leftHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    backButtonCircle: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    backArrow: {
        fontSize: 20,
        color: '#fff',
        fontWeight: 'bold',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
    },
    logoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    logoImage: {
        width: 20,
        height: 20,
        borderRadius: 4,
    },
    logoText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#fff',
    },
    searchBarRow: {
        flexDirection: 'row',
        alignItems: 'center',
        // backgroundColor: '#E8EAED',
        paddingHorizontal: 10,
        paddingVertical: 12,
    },
    searchInputContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        paddingHorizontal: 12,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#10B981',
    },
    searchIcon: {
        fontSize: 16,
        marginRight: 8,
        color: '#999',
    },
    searchInput: {
        flex: 1,
        paddingVertical: 10,
        fontSize: 14,
        color: '#333',
    },
    clearButton: {
        padding: 4,
    },
    clearIcon: {
        fontSize: 16,
        color: '#999',
    },
    filtersRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: '#fff',
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderBottomWidth: 2,
        borderBottomColor: '#E8EAED',
        elevation: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        zIndex: 1000,
    },
    filterButtonsContainer: {
        flex: 1,
        position: 'relative',
        zIndex: 2000,
    },
    filterButton: {
        backgroundColor: '#F8F9FA',
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#10B981',
    },
    filterButtonText: {
        fontSize: 13,
        fontWeight: '600',
        // color: '#2c4455',
        textAlign: 'center',
    },
    compactFiltersRow: {
        backgroundColor: '#E8EAED',
        flexDirection: 'row',
        gap: 12,
        paddingHorizontal: 16,
        paddingVertical: 0,
        alignItems: 'center',
    },
    filterSection: {
        flex: 1,
        position: 'relative',
    },
    filterHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 12,
        backgroundColor: '#fff',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#ddd',
    },
    filterHeaderText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#333',
        flex: 1,
    },
    filterHeaderArrow: {
        fontSize: 12,
        color: '#666',
        marginLeft: 5,
    },
    filterContent: {
        position: 'absolute',
        top: 40,
        left: 0,
        right: 0,
        zIndex: 3000,
        backgroundColor: '#fff',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#ddd',
        elevation: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 8,
        maxHeight: 250,
    },
    filterScrollView: {
        paddingVertical: 8,
        paddingHorizontal: 8,
    },
    filterOption: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        paddingHorizontal: 12,
        borderRadius: 8,
        backgroundColor: '#fff',
        marginBottom: 6,
    },
    filterOptionActive: {
        backgroundColor: '#10B981',
    },
    filterOptionIcon: {
        fontSize: 14,
        marginRight: 8,
        color: '#2c4455',
    },
    filterOptionText: {
        fontSize: 13,
        color: '#333',
        flex: 1,
    },
    filterOptionTextActive: {
        color: '#fff',
    },
    filterOptionCheck: {
        fontSize: 14,
        color: '#fff',
    },
    list: {
        paddingTop: 14,
        paddingBottom: 80,
        backgroundColor: '#E8EAED',
        paddingHorizontal: 12,
    },
    row: {
        justifyContent: 'space-between',
        paddingHorizontal: 0,
        gap: 12,
    },
    emptyContainer: {
        flex: 1,
        width: '100%',
        minHeight: 400,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 80,
        paddingHorizontal: 20,
        backgroundColor: '#E8EAED',
    },
    emptyContent: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 40,
        width: '100%',
        maxWidth: 400,
    },
    emptyIcon: {
        fontSize: 80,
        marginBottom: 20,
        opacity: 0.5,
    },
    emptyTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 10,
        textAlign: 'center',
    },
    emptyText: {
        fontSize: 15,
        color: '#666',
        textAlign: 'center',
        lineHeight: 22,
    },
    clearFiltersButton: {
        marginTop: 20,
        backgroundColor: '#10B981',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 25,
        elevation: 2,
        shadowColor: '#10B981',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
    },
    clearFiltersButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: 'bold',
    },
    addButton: {
        position: 'absolute',
        right: 20,
        bottom: 20,
        width: 64,
        height: 64,
        borderRadius: 32,
        elevation: 8,
        shadowColor: '#10B981',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 5,
    },
    addButtonInner: {
        width: '100%',
        height: '100%',
        borderRadius: 32,
        backgroundColor: '#10B981',
        justifyContent: 'center',
        alignItems: 'center',
    },
    addButtonText: {
        fontSize: 32,
        color: '#fff',
        fontWeight: '300',
    },
    loadMoreButton: {
        backgroundColor: '#10B981',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 25,
        alignItems: 'center',
        justifyContent: 'center',
        marginVertical: 10,
        elevation: 2,
        shadowColor: '#10B981',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
    },
    loadMoreText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
});

