import { StyleSheet, Platform } from 'react-native';
import { Colors, Spacing, FontSizes, BorderRadius, Shadows, FontWeights } from '../../constants/theme';

export const editItemStyles = StyleSheet.create({
safeContainer: {
        flex: 1,
        backgroundColor: '#F8F9FA',
        paddingTop: Platform.OS === 'android' ? 25 : 0,
    },
    headerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#E8E8E8',
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F8F9FA',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E8E8E8',
    },
    backArrow: {
        fontSize: 22,
        color: '#333',
    },
    headerTitleContainer: {
        flex: 1,
        alignItems: 'center',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#2c4455',
    },
    headerSubtitle: {
        fontSize: 12,
        color: '#666',
        marginTop: 2,
    },
    headerSpacer: {
        width: 40,
    },
    scrollContent: {
        flex: 1,
        padding: 16,
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 4,
    },
    cardSubtitle: {
        fontSize: 13,
        color: '#666',
        marginBottom: 16,
    },
    label: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        marginTop: 12,
        marginBottom: 8,
    },
    sublabel: {
        fontSize: 12,
        color: '#666',
        marginBottom: 8,
        fontStyle: 'italic',
    },
    input: {
        borderWidth: 1,
        borderColor: '#E8E8E8',
        backgroundColor: '#F8F9FA',
        padding: 14,
        borderRadius: 12,
        fontSize: 15,
        color: '#333',
    },
    multilineInput: {
        height: 100,
        textAlignVertical: 'top',
    },
    pickerContainer: {
        borderWidth: 1,
        borderColor: '#E8E8E8',
        backgroundColor: '#F8F9FA',
        borderRadius: 12,
        overflow: 'hidden',
    },
    priceInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E8E8E8',
        backgroundColor: '#F8F9FA',
        borderRadius: 12,
        paddingHorizontal: 14,
    },
    currencySymbol: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#28a745',
        marginRight: 8,
    },
    priceInput: {
        flex: 1,
        paddingVertical: 14,
        fontSize: 15,
        color: '#333',
    },
    perDay: {
        fontSize: 14,
        color: '#666',
        marginLeft: 8,
    },
    depositWarning: {
        fontSize: 12,
        color: '#FF9800',
        fontStyle: 'italic',
        marginBottom: 8,
        lineHeight: 18,
    },
    checkboxContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 8,
        marginBottom: 12,
        paddingVertical: 8,
    },
    checkbox: {
        width: 24,
        height: 24,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: '#2c4455',
        backgroundColor: '#fff',
        marginRight: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    checkboxChecked: {
        backgroundColor: '#2c4455',
    },
    checkboxIcon: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    checkboxLabel: {
        fontSize: 15,
        color: '#333',
        fontWeight: '500',
    },
    deliveryTypeContainer: {
        marginTop: 12,
        gap: 10,
    },
    deliveryOption: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        padding: 14,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#E8E8E8',
    },
    deliveryOptionActive: {
        backgroundColor: '#E3F2FD',
        borderColor: '#2c4455',
    },
    deliveryOptionIcon: {
        fontSize: 20,
        marginRight: 12,
    },
    deliveryOptionText: {
        fontSize: 15,
        color: '#666',
        fontWeight: '500',
        flex: 1,
    },
    deliveryOptionTextActive: {
        color: '#2c4455',
        fontWeight: '700',
    },
    deliveryCheckmark: {
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: '#2c4455',
        justifyContent: 'center',
        alignItems: 'center',
    },
    deliveryCheckmarkText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
    },
    photosGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginTop: 12,
        gap: 10,
    },
    photoContainer: {
        width: '31%',
        aspectRatio: 1,
    },
    photoPlaceholder: {
        width: '100%',
        height: '100%',
        borderWidth: 2,
        borderColor: '#E8E8E8',
        borderStyle: 'dashed',
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        overflow: 'hidden',
    },
    photoPlaceholderPrimary: {
        borderColor: '#2c4455',
        borderStyle: 'solid',
        borderWidth: 2,
    },
    addPhotoContent: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    addPhotoIcon: {
        fontSize: 28,
        marginBottom: 4,
    },
    addPhotoText: {
        fontSize: 10,
        color: '#666',
        textAlign: 'center',
        fontWeight: '600',
    },
    previewImage: {
        width: '100%',
        height: '100%',
        borderRadius: 10,
    },
    removePhotoButton: {
        position: 'absolute',
        top: 4,
        right: 4,
        backgroundColor: 'rgba(220, 53, 69, 0.9)',
        width: 22,
        height: 22,
        borderRadius: 11,
        justifyContent: 'center',
        alignItems: 'center',
    },
    removePhotoText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
    },
    primaryBadge: {
        position: 'absolute',
        bottom: 4,
        left: 4,
        backgroundColor: 'rgba(44, 68, 85, 0.9)',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
    },
    primaryBadgeText: {
        color: '#fff',
        fontSize: 8,
        fontWeight: 'bold',
    },
    publishButton: {
        marginTop: 8,
        marginBottom: 8,
        borderRadius: 16,
        overflow: 'hidden',
        elevation: 8,
        shadowColor: '#10B981',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
    },
    publishButtonDisabled: {
        opacity: 0.7,
    },
    publishButtonGradient: {
        paddingVertical: 18,
        paddingHorizontal: 24,
        alignItems: 'center',
        justifyContent: 'center',
    },
    publishButtonContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
    },
    publishButtonIcon: {
        fontSize: 24,
    },
    publishButtonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },
    loadingAddressContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: '#F8F9FA',
        borderRadius: 8,
        marginTop: 8,
        gap: 10,
    },
    loadingAddressText: {
        fontSize: 14,
        color: '#666',
        fontStyle: 'italic',
    },
    suggestionsContainer: {
        backgroundColor: '#fff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#E8E8E8',
        marginTop: 12,
        padding: 12,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    suggestionsTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#2c4455',
        marginBottom: 10,
    },
    suggestionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: '#F8F9FA',
        borderRadius: 8,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#E8E8E8',
    },
    suggestionIcon: {
        fontSize: 18,
        marginRight: 10,
    },
    suggestionText: {
        fontSize: 14,
        color: '#333',
        flex: 1,
    },
    selectedLocationContainer: {
        marginTop: 12,
    },
    selectedLocationLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#2c4455',
        marginBottom: 8,
    },
    selectedLocationBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#E8F5E9',
        padding: 14,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#10B981',
    },
    selectedLocationIcon: {
        fontSize: 20,
        marginRight: 10,
    },
    selectedLocationText: {
        fontSize: 15,
        color: '#2c4455',
        fontWeight: '500',
        flex: 1,
    },
    clearLocationButton: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#dc3545',
        justifyContent: 'center',
        alignItems: 'center',
    },
    clearLocationText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    // Estilos para disponibilidade de horários
    subLabel: {
        fontSize: 14,
        color: '#555',
        fontWeight: '600',
        marginTop: 16,
        marginBottom: 8,
    },
    daysContainer: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 16,
    },
    dayButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#DDD',
        backgroundColor: '#F8F9FA',
        alignItems: 'center',
    },
    dayButtonActive: {
        backgroundColor: '#10B981',
        borderColor: '#10B981',
    },
    dayButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#666',
    },
    dayButtonTextActive: {
        color: '#fff',
    },
    timeRangeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 8,
    },
    timePickerButton: {
        flex: 1,
        backgroundColor: '#F8F9FA',
        borderWidth: 1,
        borderColor: '#DDD',
        borderRadius: 8,
        padding: 12,
    },
    timePickerLabel: {
        fontSize: 12,
        color: '#666',
        marginBottom: 4,
    },
    timePickerValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
    },
    timeRangeSeparator: {
        fontSize: 20,
        color: '#666',
        fontWeight: 'bold',
    },
    deliveryDetailsContainer: {
        marginTop: 20,
        padding: 16,
        backgroundColor: '#F8F9FA',
        borderRadius: 12,
        borderLeftWidth: 4,
        borderLeftColor: '#10B981',
    },
    deliveryDetailsTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 12,
    },
    deliveryFeeTypeContainer: {
        flexDirection: 'row',
        gap: 8,
        marginTop: 8,
        marginBottom: 12,
    },
    deliveryFeeOption: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#fff',
        padding: 10,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#E8E8E8',
        gap: 6,
        minHeight: 44,
    },
    deliveryFeeOptionActive: {
        backgroundColor: '#E8F5E9',
        borderColor: '#10B981',
    },
    deliveryFeeIcon: {
        fontSize: 16,
    },
    deliveryFeeText: {
        fontSize: 12,
        fontWeight: '600',
        color: '#666',
        flexShrink: 1,
    },
    deliveryFeeTextActive: {
        color: '#10B981',
    },
    smallCheckmark: {
        width: 20,
        height: 20,
        borderRadius: 10,
        backgroundColor: '#10B981',
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 4,
    },
    smallCheckmarkText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
    },
});
