import { StyleSheet, Platform, StatusBar } from 'react-native';

export const homeStyles = StyleSheet.create({
backgroundImage: {
        flex: 1,
        alignSelf: 'stretch',
    },
    container: {
        flex: 1,
        backgroundColor: '#f2f2f2',
        paddingTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 0) + 10 : 35,
        paddingBottom: Platform.OS === 'android' ? 80 : 0, // Espaço para menu do app não ser coberto
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#fff',
        paddingHorizontal: 20,
        paddingVertical: 15,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.1,
        shadowRadius: 3,
    },
    menuButton: {
        padding: 5,
        position: 'relative',
    },
    notificationDot: {
        position: 'absolute',
        top: 0,
        right: 0,
        backgroundColor: '#dc3545',
        borderRadius: 10,
        minWidth: 20,
        height: 20,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#fff',
    },
    notificationDotText: {
        color: '#fff',
        fontSize: 11,
        fontWeight: 'bold',
    },
    hamburger: {
        width: 28,
        height: 20,
        justifyContent: 'space-between',
    },
    hamburgerLine: {
        height: 1.5,
        alignSelf: 'stretch',
        backgroundColor: '#333',
        borderRadius: 1,
    },
    headerTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    titleTextContainer: {
        flexDirection: 'column',
        alignItems: 'center',
    },
    headerIcon: {
        width: 28,
        height: 28,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#2c4455',
    },
    headerSubtitle: {
        fontSize: 11,
        fontWeight: '600',
        color: '#10B981',
        textAlign: 'center',
        lineHeight: 14,
        marginTop: 2,
    },
    profileButton: {
        padding: 5,
    },
    content: {
        flex: 1,
    },
    heroCarouselContainer: {
        width: '500',
        height: 610,
        overflow: 'hidden',
    },
    heroScrollView: {
        width: '500',
        height: 650,
    },
    heroSection: {
        padding: 0,
        flex: 1,
    },
    heroSectionBackground: {
        width: '380',
        height: 580,
    },
    heroCard: {

        borderRadius: 20,
        padding: 30,
        alignItems: 'center',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    heroTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#1a3a52',
        textAlign: 'center',
        lineHeight: 28,
    },
    heroSubtitle: {
        fontSize: 14,
        color: '#666',
        textAlign: 'center',
        marginTop: 4,
        lineHeight: 20,
    },
    heroSpacer: {
        height: 150,
        marginVertical: -10,
    },
    heroButtonsContainer: {
        flexDirection: 'row',
        marginTop: 50,
        marginBottom: 10,
        gap: 12,
    },
    heroButton: {
        flex: 1,
        paddingVertical: 14,
        paddingHorizontal: 24,
        borderRadius: 25,
    },
    heroButtonExplorar: {
        backgroundColor: '#FF6347',
    },
    heroButtonAnunciar: {
        backgroundColor: '#10B981',
    },
    heroButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    carouselIndicators: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 20,
        gap: 10,
    },
    carouselDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: '#ccc',
    },
    carouselDotActive: {
        backgroundColor: '#10B981',
        width: 12,
        height: 12,
        borderRadius: 6,
    },
    searchContainer: {
        flexDirection: 'row',
        marginHorizontal: 10,
        marginVertical: -3,
        maxWidth: '95%',
        alignSelf: 'center',
        backgroundColor: '#fff',
        borderRadius: 25,
        paddingHorizontal: 15,
        paddingVertical: 5,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.1,
        shadowRadius: 2,
        borderColor: '#10B981',

    },
    searchInput: {
        flex: 1,
        paddingVertical: 10,
        fontSize: 16,
    },
    searchButton: {
        justifyContent: 'center',
        paddingHorizontal: 10,
    },
    searchIcon: {
        fontSize: 20,
    },
    section: {
        marginTop: 0,
        paddingHorizontal: 20,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingHorizontal: 0,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#2c4455',
    },
    viewAllButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#10B981',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 16,
        gap: 4,
    },
    viewAllButtonText: {
        fontSize: 12,
        color: '#fff',
        fontWeight: '600',
    },
    viewAllButtonIcon: {
        fontSize: 14,
        color: '#fff',
        fontWeight: 'bold',
    },
    categoriesContainer: {
        backgroundColor: '#fff',
        borderRadius: 16,
        paddingTop: 20,
        paddingBottom: 40,
        paddingHorizontal: 15,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.08,
        shadowRadius: 4,
    },
    categoriesGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    categoryCard: {
        width: '31%',
        aspectRatio: 1,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 12,
        padding: 12,
        backgroundColor: '#fff',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 2},
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    categoryIconContainer: {
        width: 64,
        height: 64,
        borderRadius: 32,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
    },
    categoryIcon: {
        fontSize: 32,
        marginBottom: 5,
    },
    categoryName: {
        fontSize: 10,
        fontWeight: '600',
        color: '#2c4455',
        textAlign: 'center',
    },
    browseButton: {
        backgroundColor: '#007bff',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
    },
    browseButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    quickActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        marginTop: 20,
        marginBottom: 30,
        gap: 15,
    },
    quickActionButton: {
        flex: 1,
        backgroundColor: '#fff',
        padding: 20,
        borderRadius: 15,
        alignItems: 'center',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: {width: 0, height: 1},
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    quickActionIcon: {
        fontSize: 32,
        marginBottom: 10,
    },
    quickActionText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        textAlign: 'center',
    },
    menuOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-start',
    },
    menuContainer: {
        width: '75%',
        height: '100%',
        backgroundColor: '#fff',
        paddingTop: 50,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: {width: 2, height: 0},
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    menuDrawer: {
        width: '75%',
        height: '100%',
        backgroundColor: '#fff',
        paddingTop: 50,
    },
    closeButton: {
        padding: 8,
    },
    closeButtonText: {
        fontSize: 24,
        color: '#666',
    },
    menuHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    menuTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#2c4455',
    },
    menuSubtitle: {
        fontSize: 14,
        color: '#666',
    },
    menuItems: {
        paddingTop: 20,
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 15,
    },
    menuItemIcon: {
        fontSize: 24,
        marginRight: 15,
        width: 30,
    },
    menuItemText: {
        fontSize: 16,
        color: '#333',
        fontWeight: '500',
    },
    menuBadge: {
        position: 'absolute',
        right: 20,
        backgroundColor: '#10B981',
        borderRadius: 12,
        minWidth: 24,
        height: 24,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 6,
    },
    menuBadgeText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
    },
    menuDivider: {
        height: 1,
        backgroundColor: '#e0e0e0',
        marginVertical: 10,
        marginHorizontal: 20,
    },
    userNotificationDot: {
        position: 'absolute',
        top: 0,
        right: 0,
        backgroundColor: '#dc3545',
        borderRadius: 10,
        minWidth: 20,
        height: 20,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#fff',
    },
    userNotificationDotText: {
        color: '#fff',
        fontSize: 11,
        fontWeight: 'bold',
    },
    // Tab Bar
    tabBar: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
        paddingBottom: Platform.OS === 'android' ? 0 : 0,
        paddingTop: 5,
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    tabButton: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: 6,
        position: 'relative',
    },
    tabLabel: {
        fontSize: 11,
        color: '#9CA3AF',
        marginTop: 4,
        fontWeight: '500',
    },
    tabBadge: {
        position: 'absolute',
        top: 0,
        right: '25%',
        backgroundColor: '#EF4444',
        borderRadius: 10,
        minWidth: 18,
        height: 18,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#fff',
    },
    tabBadgeText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: 'bold',
    },
});
