import { StyleSheet, Platform } from 'react-native';

export const itemDetailsStyles = StyleSheet.create({
safeContainer: {
        flex: 1,
        backgroundColor: '#E8EAED',
        paddingTop: Platform.OS === 'android' ? 25 : 0,
    },
    // Header Verde - Mesmo layout do Marketplace
    headerContainer: {
        backgroundColor: '#10B981',
        paddingTop: 12,
        paddingBottom: 12,
        paddingHorizontal: 16,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
    },
    headerTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    leftHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    backButtonCircle: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    backArrow: {
        fontSize: 20,
        color: '#fff',
        fontWeight: 'bold',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
    },
    logoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    logoImage: {
        width: 20,
        height: 20,
        borderRadius: 4,
    },
    logoText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#fff',
    },
    scrollContainer: {
        flex: 1,
        backgroundColor: '#E8EAED',
    },
    cardContainer: {
        backgroundColor: '#fff',
        marginHorizontal: 16,
        marginTop: 16,
        marginBottom: 16,
        borderRadius: 12,
        overflow: 'hidden',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    noPhotoContainer: {
        width: '100%',
        height: 300,
        backgroundColor: '#F8F9FA',
        justifyContent: 'center',
        alignItems: 'center',
    },
    noPhotoText: {
        fontSize: 60,
        marginBottom: 10,
    },
    noPhotoLabel: {
        fontSize: 16,
        color: '#666',
    },
    contentContainer: {
        padding: 20,
    },
    categoryBadgeContainer: {
        flexDirection: 'row',
        marginBottom: 12,
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#333',
        textAlign: 'left',
    },
    priceContainer: {
        flexDirection: 'row',
        alignItems: 'baseline',
        marginBottom: 15,
    },
    price: {
        fontSize: 32,
        fontWeight: 'bold',
        color: '#10B981',
    },
    priceLabel: {
        fontSize: 18,
        color: '#6c757d',
    },
    infoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
        gap: 10,
    },
    badge: {
        backgroundColor: '#007bff',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 15,
        alignSelf: 'flex-start',
    },
    badgeText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: '600',
    },
    location: {
        fontSize: 14,
        color: '#6c757d',
    },
    locationText: {
        fontSize: 16,
        color: '#495057',
        lineHeight: 24,
        textAlign: 'left',
    },
    section: {
        marginTop: 20,
        paddingTop: 20,
        borderTopWidth: 1,
        borderTopColor: '#e9ecef',
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 10,
        color: '#2c4455',
        textAlign: 'left',
    },
    description: {
        fontSize: 16,
        lineHeight: 24,
        color: '#495057',
        textAlign: 'left',
    },
    ownerCard: {
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
        padding: 15,
        borderRadius: 10,
    },
    ownerCardLeft: {
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        backgroundColor: 'transparent',
        padding: 0,
    },
    ownerInfo: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    ownerName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
        textAlign: 'center',
        marginBottom: 8,
    },
    ownerNameLeft: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        textAlign: 'left',
        marginBottom: 8,
    },
    contactButton: {
        backgroundColor: '#2c4455',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
    },
    contactButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    starsContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 5,
    },
    starsContainerLeft: {
        justifyContent: 'flex-start',
        alignItems: 'flex-start',
        marginTop: 5,
    },
    starsRow: {
        flexDirection: 'row',
        justifyContent: 'center',
    },
    starIcon: {
        fontSize: 16,
        marginRight: 2,
    },
    ratingNumber: {
        marginTop: 6,
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
        textAlign: 'left',
    },
    infoItem: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 8,
    },
    infoLabel: {
        fontSize: 14,
        color: '#6c757d',
    },
    infoValue: {
        fontSize: 14,
        fontWeight: '600',
        color: '#333',
    },
    actionButtons: {
        marginTop: 30,
        gap: 10,
    },
    primaryButton: {
        backgroundColor: '#28a745',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
    },
    primaryButtonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    secondaryButton: {
        backgroundColor: '#fff',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#007bff',
    },
    secondaryButtonText: {
        color: '#007bff',
        fontSize: 16,
        fontWeight: '600',
    },
    deliveryOptionsContainer: {
        backgroundColor: '#F8F9FA',
        padding: 16,
        borderRadius: 12,
        borderLeftWidth: 4,
        borderLeftColor: '#10B981',
    },
    deliveryOption: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
        gap: 10,
    },
    deliveryOptionIcon: {
        fontSize: 18,
        color: '#10B981',
        fontWeight: 'bold',
    },
    deliveryOptionText: {
        fontSize: 15,
        color: '#333',
        fontWeight: '500',
    },
    deliveryNote: {
        fontSize: 13,
        color: '#666',
        fontStyle: 'italic',
        marginTop: 8,
        paddingTop: 8,
        borderTopWidth: 1,
        borderTopColor: '#E0E0E0',
    },
    orText: {
        fontSize: 14,
        fontWeight: 'bold',
        color: '#999',
        textAlign: 'center',
        marginVertical: 8,
    },
    // Estilos para Descontos
    discountContainer: {
        backgroundColor: '#FFF3E0',
        padding: 16,
        borderRadius: 12,
        borderLeftWidth: 4,
        borderLeftColor: '#FF9800',
        marginTop: 20,
        marginBottom: 10,
    },
    discountTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#E65100',
        marginBottom: 12,
        textAlign: 'left',
    },
    discountItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
        gap: 10,
    },
    discountIcon: {
        fontSize: 20,
    },
    discountText: {
        fontSize: 15,
        color: '#333',
        flex: 1,
    },
    discountBold: {
        fontWeight: 'bold',
        color: '#E65100',
        fontSize: 16,
    },
});
