import { StyleSheet, Platform } from 'react-native';
import { Colors, Spacing, FontSizes, BorderRadius, Shadows, FontWeights } from '../../constants/theme';

export const myRentalsStyles = StyleSheet.create({
container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
        paddingTop: Platform.OS === 'android' ? 25 : 0,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 16,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#E8E8E8',
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#F8F9FA',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E8E8E8',
    },
    backArrow: {
        fontSize: 22,
        color: '#333',
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#2c4455',
    },
    headerSpacer: {
        width: 40,
    },
    mainTabsContainer: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        paddingHorizontal: 8,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#E8E8E8',
        gap: 8,
    },
    mainTab: {
        flex: 1,
        paddingVertical: 12,
        paddingHorizontal: 8,
        alignItems: 'center',
        borderRadius: 8,
        backgroundColor: '#F8F9FA',
        borderWidth: 2,
        borderColor: 'transparent',
    },
    mainTabActive: {
        backgroundColor: '#E8F5E9',
        borderColor: '#10B981',
    },
    mainTabText: {
        fontSize: 14,
        color: '#666',
        fontWeight: '600',
        marginBottom: 2,
    },
    mainTabTextActive: {
        color: '#10B981',
        fontWeight: 'bold',
    },
    mainTabSubtext: {
        fontSize: 10,
        color: '#999',
        fontStyle: 'italic',
    },
    tabsContainer: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#E8E8E8',
    },
    tab: {
        flex: 1,
        paddingVertical: 10,
        alignItems: 'center',
        borderBottomWidth: 2,
        borderBottomColor: 'transparent',
    },
    tabActive: {
        borderBottomColor: '#2c4455',
    },
    tabText: {
        fontSize: 13,
        color: '#666',
        fontWeight: '500',
    },
    tabTextActive: {
        color: '#2c4455',
        fontWeight: 'bold',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 40,
    },
    emptyIcon: {
        fontSize: 64,
        marginBottom: 16,
    },
    emptyTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 8,
    },
    emptyText: {
        fontSize: 14,
        color: '#666',
        textAlign: 'center',
    },
    list: {
        flex: 1,
    },
    listContent: {
        padding: 16,
        gap: 16,
    },
    rentalCard: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    rentalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    rentalTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
        flex: 1,
    },
    statusBadge: {
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 12,
    },
    statusPending: {
        backgroundColor: '#FEF3C7',
    },
    statusApproved: {
        backgroundColor: '#D1FAE5',
    },
    statusActive: {
        backgroundColor: '#DBEAFE',
    },
    statusCompleted: {
        backgroundColor: '#E0E7FF',
    },
    statusRejected: {
        backgroundColor: '#FEE2E2',
    },
    statusCancelled: {
        backgroundColor: '#F3F4F6',
    },
    statusExpired: {
        backgroundColor: '#FED7AA',
    },
    statusText: {
        fontSize: 10,
        fontWeight: 'bold',
        color: '#333',
    },
    rentalInfo: {
        flexDirection: 'row',
        marginBottom: 8,
    },
    rentalLabel: {
        fontSize: 14,
        color: '#666',
        width: 120,
    },
    rentalValue: {
        fontSize: 14,
        color: '#333',
        fontWeight: '500',
        flex: 1,
    },
    actionButtons: {
        flexDirection: 'row',
        marginTop: 12,
        gap: 12,
    },
    approveButton: {
        flex: 1,
        backgroundColor: '#10B981',
        borderRadius: 8,
        paddingVertical: 12,
        alignItems: 'center',
    },
    approveButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    rejectButton: {
        flex: 1,
        backgroundColor: '#EF4444',
        borderRadius: 8,
        paddingVertical: 12,
        alignItems: 'center',
    },
    rejectButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    ownerAmount: {
        color: '#10B981',
        fontWeight: 'bold',
        fontSize: 15,
    },
    codesContainer: {
        marginTop: 12,
        padding: 12,
        backgroundColor: '#F0F9FF',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#BFDBFE',
    },
    codeBox: {
        marginBottom: 8,
    },
    codeLabel: {
        fontSize: 12,
        color: '#666',
        marginBottom: 4,
    },
    codeValue: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#2c4455',
        letterSpacing: 4,
        textAlign: 'center',
        paddingVertical: 8,
        backgroundColor: '#fff',
        borderRadius: 6,
        borderWidth: 2,
        borderColor: '#10B981',
        borderStyle: 'dashed',
    },
    codeHint: {
        fontSize: 11,
        color: '#666',
        marginTop: 4,
        fontStyle: 'italic',
        textAlign: 'center',
    },
    editButton: {
        flex: 1,
        backgroundColor: '#3B82F6',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
        marginRight: 8,
    },
    editButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    cancelButton: {
        flex: 1,
        backgroundColor: '#EF4444',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 8,
    },
    cancelButtonText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'center',
    },
});
