import { StyleSheet, Platform } from 'react-native';

export const requestRentalStyles = StyleSheet.create({
safeContainer: {
        flex: 1,
        backgroundColor: '#F5F5F5',
        paddingTop: Platform.OS === 'android' ? 25 : 0,
    },
    headerContainer: {
        backgroundColor: '#10B981',
        paddingHorizontal: 16,
        paddingVertical: 14,
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.1,
                shadowRadius: 4,
            },
            android: {
                elevation: 4,
            },
        }),
    },
    headerTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    leftHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        flex: 1,
    },
    backButtonCircle: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    backArrow: {
        fontSize: 22,
        color: '#fff',
        fontWeight: 'bold',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
    },
    logoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    logoImage: {
        width: 24,
        height: 24,
        borderRadius: 6,
    },
    logoText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#fff',
    },
    container: {
        flex: 1,
        backgroundColor: '#F5F5F5',
    },
    content: {
        padding: 16,
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    cardTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#2c4455',
        marginBottom: 16,
    },
    itemTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#2c4455',
        marginBottom: 8,
    },
    itemPrice: {
        fontSize: 20,
        color: '#10B981',
        fontWeight: 'bold',
        marginBottom: 6,
    },
    ownerName: {
        fontSize: 14,
        color: '#666',
    },
    selectDatesButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#007bff',
        padding: 16,
        borderRadius: 12,
        marginBottom: 12,
    },
    selectDatesText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    calendarContainer: {
        marginTop: 8,
    },
    timeContainer: {
        marginBottom: 16,
    },
    timeLabel: {
        fontSize: 15,
        fontWeight: '600',
        color: '#2c4455',
        marginBottom: 10,
    },
    timeSelector: {
        marginTop: 4,
    },
    timeButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        padding: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#10B981',
        gap: 12,
    },
    timeIcon: {
        fontSize: 24,
    },
    timeValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#10B981',
    },
    summaryCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
        borderLeftWidth: 4,
        borderLeftColor: '#10B981',
    },
    summaryTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#2c4455',
        marginBottom: 16,
    },
    summaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    summaryLabel: {
        fontSize: 16,
        color: '#495057',
    },
    summaryValue: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
    },
    discountLabel: {
        fontSize: 15,
        fontWeight: '600',
        color: '#10B981',
        flex: 1,
    },
    discountValue: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#10B981',
    },
    divider: {
        height: 1,
        backgroundColor: '#adb5bd',
        marginVertical: 15,
    },
    totalLabel: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
    },
    totalValue: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#28a745',
    },
    taxIncludedNote: {
        marginTop: 8,
        padding: 10,
        backgroundColor: '#E8F5E9',
        borderRadius: 8,
        borderLeftWidth: 3,
        borderLeftColor: '#10B981',
    },
    taxIncludedText: {
        fontSize: 13,
        color: '#10B981',
        fontWeight: '600',
        textAlign: 'center',
    },
    depositContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
    },
    depositLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#FF9800',
    },
    depositValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#FF9800',
    },
    depositNote: {
        fontSize: 13,
        color: '#666',
        fontStyle: 'italic',
        lineHeight: 19,
        marginTop: 8,
        paddingVertical: 10,
        paddingHorizontal: 10,
        backgroundColor: '#FFF3E0',
        borderRadius: 8,
        borderLeftWidth: 3,
        borderLeftColor: '#FF9800',
    },
    confirmButton: {
        backgroundColor: '#28a745',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
        marginBottom: 10,
    },
    confirmButtonText: {
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    cancelButton: {
        backgroundColor: '#fff',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#dc3545',
    },
    cancelButtonText: {
        color: '#dc3545',
        fontSize: 16,
        fontWeight: '600',
    },
    deliveryMethodContainer: {
        flexDirection: 'row',
        gap: 10,
        marginBottom: 15,
    },
    deliveryMethodOption: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        backgroundColor: '#fff',
        padding: 16,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#E8E8E8',
        minHeight: 100,
        justifyContent: 'center',
    },
    deliveryMethodActive: {
        backgroundColor: '#E8F5E9',
        borderColor: '#10B981',
    },
    deliveryMethodIcon: {
        fontSize: 28,
        marginBottom: 8,
    },
    deliveryMethodTextContainer: {
        alignItems: 'center',
    },
    deliveryMethodText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#666',
        textAlign: 'center',
    },
    deliveryMethodTextActive: {
        color: '#10B981',
    },
    deliveryMethodSubtext: {
        fontSize: 11,
        color: '#999',
        marginTop: 4,
    },
    deliveryMethodCheck: {
        position: 'absolute',
        top: 8,
        right: 8,
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: '#10B981',
        justifyContent: 'center',
        alignItems: 'center',
    },
    deliveryMethodCheckText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: 'bold',
    },
    deliveryNote: {
        fontSize: 13,
        color: '#666',
        fontStyle: 'italic',
        backgroundColor: '#F8F9FA',
        padding: 10,
        borderRadius: 8,
        borderLeftWidth: 3,
        borderLeftColor: '#10B981',
    },
    freeDeliveryLabel: {
        fontSize: 15,
        fontWeight: '600',
        color: '#10B981',
    },
    freeDeliveryValue: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#10B981',
    },
});
